version: '3'

services:
  postgresql_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_PASSWORD: "posgre"
    container_name: postgresql
    ports:
      - "5432:5432"
    networks:
      my_net:
        ipv4_address: 10.0.101.10

  psql:
    image: postgres:9
    container_name: psql
    networks:
      my_net:
        ipv4_address: 10.0.101.11
    command: tail -f /dev/null

  pgbench-init:
    image: postgres:9
    container_name: pgbench-init
    networks:
      my_net:
        ipv4_address: 10.0.101.12
    environment:
      PGAPPNAME: pgbench
      PGHOST: 10.0.101.10
      PGUSER: pgadmin
      PGPASSWORD: posgre
      PGDATABASE: pgbench
    command: bash -c "dropdb pgbench && createdb --owner=pgadmin pgbench && pgbench -i -s 5"

  pgbench:
    image: postgres:9
    container_name: pgbench
    networks:
      my_net:
        ipv4_address: 10.0.101.13
    environment:
      PGAPPNAME: pgbench
      PGHOST: 10.0.101.10
      PGUSER: pgadmin
      PGPASSWORD: posgre
      PGDATABASE: pgbench
    command: [
      "pgbench",
        "-c", "10",
        "-s", "5",
        "-R", "10",
        "-j", "2",
        "-T", "100",
        "-b", "tpcb-like",
        "-P", "1",
        "--report-latencies",
        "pgbench"
    ]

  go_test:
    build:
      context: tests
      dockerfile: Dockerfile
    container_name: go-test
    environment:
      - DB_HOST=10.0.101.10
      - DB_PASSWORD=posgre
    networks:
      my_net:
        ipv4_address: 10.0.101.14
    command: tail -f /dev/null

networks:
  my_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.0.101.0/24
