version: '3.4'

x-common_environment: &common_environment
  PGAPPNAME: pgbench
  PGHOST: 10.0.101.10
  PGUSER: pgadmin
  PGPASSWORD: posgre
  PGDATABASE: pgbench
x-networks: &common_networks
  networks:
    my_net:

services:
  postgresql_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_PASSWORD: "posgre"
    container_name: postgresql
    ports:
      - "5432:5432"
    networks:
      my_net:
        ipv4_address: 10.0.101.10

  psql:
    image: postgres:9
    container_name: psql
    environment: *common_environment
    <<: *common_networks

  pgbench-prepare:
    image: postgres:9
    container_name: pgbench-prepare
    environment: *common_environment
    command: bash -c "dropdb pgbench ; createdb --owner=pgadmin pgbench && pgbench --initialize --scale=5"
    <<: *common_networks

  pgbench-teardown:
    image: postgres:9
    container_name: pgbench-teardown
    environment: *common_environment
    command: bash -c "dropdb pgbench"
    <<: *common_networks

  pgbench:
    image: postgres:9
    container_name: pgbench
    environment: *common_environment
    volumes:
      - ./benchmark:/work/benchmark
    command: bash -c "pgbench --client=1 --jobs=2 --time=10 --progress=1 --log --report-latencies pgbench"
    <<: *common_networks

  rdspara:
    build:
      context: rdspara
      dockerfile: Dockerfile
    container_name: rdspara
    <<: *common_networks

  go_test:
    build:
      context: tests
      dockerfile: Dockerfile
    container_name: go-test
    environment:
      DB_HOST: 10.0.101.10
      DB_PASSWORD: posgre
    <<: *common_networks

networks:
  my_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.0.101.0/24
